image:
  repository: nginx  # will be overridden by Jenkins pipeline
  tag: latest

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
